image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - cmd: java -jar ./artifacts/app-ibank.jar -P:profile=test
  - ps: Start running app-ibank application!!!

build_script:
  - ./gradlew test -Dselenide.headless=true --info